package pojo;
// Generated 16/10/2017 20:07:53 by Hibernate Tools 4.3.1



/**
 * PacientePossuiDispositivo generated by hbm2java
 */
public class PacientePossuiDispositivo  implements java.io.Serializable {


     private PacientePossuiDispositivoId id;

    public PacientePossuiDispositivo() {
    }

    public PacientePossuiDispositivo(PacientePossuiDispositivoId id) {
       this.id = id;
    }
   
    public PacientePossuiDispositivoId getId() {
        return this.id;
    }
    
    public void setId(PacientePossuiDispositivoId id) {
        this.id = id;
    }




}


