package pojo;
// Generated 16/10/2017 20:07:53 by Hibernate Tools 4.3.1



/**
 * PacientePossuiTrauma generated by hbm2java
 */
public class PacientePossuiTrauma  implements java.io.Serializable {


     private PacientePossuiTraumaId id;

    public PacientePossuiTrauma() {
    }

    public PacientePossuiTrauma(PacientePossuiTraumaId id) {
       this.id = id;
    }
   
    public PacientePossuiTraumaId getId() {
        return this.id;
    }
    
    public void setId(PacientePossuiTraumaId id) {
        this.id = id;
    }




}


