package pojos;
// Generated 20/09/2017 13:38:33 by Hibernate Tools 4.3.1



/**
 * PacientePossuiTraumaId generated by hbm2java
 */
public class PacientePossuiTraumaId  implements java.io.Serializable {


     private int pacId;
     private int traId;

    public PacientePossuiTraumaId() {
    }

    public PacientePossuiTraumaId(int pacId, int traId) {
       this.pacId = pacId;
       this.traId = traId;
    }
   
    public int getPacId() {
        return this.pacId;
    }
    
    public void setPacId(int pacId) {
        this.pacId = pacId;
    }
    public int getTraId() {
        return this.traId;
    }
    
    public void setTraId(int traId) {
        this.traId = traId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PacientePossuiTraumaId) ) return false;
		 PacientePossuiTraumaId castOther = ( PacientePossuiTraumaId ) other; 
         
		 return (this.getPacId()==castOther.getPacId())
 && (this.getTraId()==castOther.getTraId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPacId();
         result = 37 * result + this.getTraId();
         return result;
   }   


}


