package pojos;
// Generated 20/09/2017 13:38:33 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbPaciente generated by hbm2java
 */
public class TbPaciente  implements java.io.Serializable {


     private Integer pacId;
     private String pacNome;
     private String pacSexo;
     private String pacDataNasc;
     private String pacEstadoCivil;
     private String pacEndereco;
     private String pacBairro;
     private String pacCidade;
     private String pacTelefoneResidencial;
     private String pacTelefoneCelular;
     private String pacEmail;
     private String pacMedicoResponsavel;
     private String pacEncaminhamentoMedico;
     private String pacPlanoSaude;
     private String pacTriadoPor;
     private Date pacDataTriagem;

    public TbPaciente() {
    }

	
    public TbPaciente(String pacNome, String pacSexo, String pacDataNasc, String pacEstadoCivil, String pacEndereco, String pacBairro, String pacCidade, String pacMedicoResponsavel, String pacEncaminhamentoMedico, String pacPlanoSaude, String pacTriadoPor, Date pacDataTriagem) {
        this.pacNome = pacNome;
        this.pacSexo = pacSexo;
        this.pacDataNasc = pacDataNasc;
        this.pacEstadoCivil = pacEstadoCivil;
        this.pacEndereco = pacEndereco;
        this.pacBairro = pacBairro;
        this.pacCidade = pacCidade;
        this.pacMedicoResponsavel = pacMedicoResponsavel;
        this.pacEncaminhamentoMedico = pacEncaminhamentoMedico;
        this.pacPlanoSaude = pacPlanoSaude;
        this.pacTriadoPor = pacTriadoPor;
        this.pacDataTriagem = pacDataTriagem;
    }
    public TbPaciente(String pacNome, String pacSexo, String pacDataNasc, String pacEstadoCivil, String pacEndereco, String pacBairro, String pacCidade, String pacTelefoneResidencial, String pacTelefoneCelular, String pacEmail, String pacMedicoResponsavel, String pacEncaminhamentoMedico, String pacPlanoSaude, String pacTriadoPor, Date pacDataTriagem) {
       this.pacNome = pacNome;
       this.pacSexo = pacSexo;
       this.pacDataNasc = pacDataNasc;
       this.pacEstadoCivil = pacEstadoCivil;
       this.pacEndereco = pacEndereco;
       this.pacBairro = pacBairro;
       this.pacCidade = pacCidade;
       this.pacTelefoneResidencial = pacTelefoneResidencial;
       this.pacTelefoneCelular = pacTelefoneCelular;
       this.pacEmail = pacEmail;
       this.pacMedicoResponsavel = pacMedicoResponsavel;
       this.pacEncaminhamentoMedico = pacEncaminhamentoMedico;
       this.pacPlanoSaude = pacPlanoSaude;
       this.pacTriadoPor = pacTriadoPor;
       this.pacDataTriagem = pacDataTriagem;
    }
   
    public Integer getPacId() {
        return this.pacId;
    }
    
    public void setPacId(Integer pacId) {
        this.pacId = pacId;
    }
    public String getPacNome() {
        return this.pacNome;
    }
    
    public void setPacNome(String pacNome) {
        this.pacNome = pacNome;
    }
    public String getPacSexo() {
        return this.pacSexo;
    }
    
    public void setPacSexo(String pacSexo) {
        this.pacSexo = pacSexo;
    }
    public String getPacDataNasc() {
        return this.pacDataNasc;
    }
    
    public void setPacDataNasc(String pacDataNasc) {
        this.pacDataNasc = pacDataNasc;
    }
    public String getPacEstadoCivil() {
        return this.pacEstadoCivil;
    }
    
    public void setPacEstadoCivil(String pacEstadoCivil) {
        this.pacEstadoCivil = pacEstadoCivil;
    }
    public String getPacEndereco() {
        return this.pacEndereco;
    }
    
    public void setPacEndereco(String pacEndereco) {
        this.pacEndereco = pacEndereco;
    }
    public String getPacBairro() {
        return this.pacBairro;
    }
    
    public void setPacBairro(String pacBairro) {
        this.pacBairro = pacBairro;
    }
    public String getPacCidade() {
        return this.pacCidade;
    }
    
    public void setPacCidade(String pacCidade) {
        this.pacCidade = pacCidade;
    }
    public String getPacTelefoneResidencial() {
        return this.pacTelefoneResidencial;
    }
    
    public void setPacTelefoneResidencial(String pacTelefoneResidencial) {
        this.pacTelefoneResidencial = pacTelefoneResidencial;
    }
    public String getPacTelefoneCelular() {
        return this.pacTelefoneCelular;
    }
    
    public void setPacTelefoneCelular(String pacTelefoneCelular) {
        this.pacTelefoneCelular = pacTelefoneCelular;
    }
    public String getPacEmail() {
        return this.pacEmail;
    }
    
    public void setPacEmail(String pacEmail) {
        this.pacEmail = pacEmail;
    }
    public String getPacMedicoResponsavel() {
        return this.pacMedicoResponsavel;
    }
    
    public void setPacMedicoResponsavel(String pacMedicoResponsavel) {
        this.pacMedicoResponsavel = pacMedicoResponsavel;
    }
    public String getPacEncaminhamentoMedico() {
        return this.pacEncaminhamentoMedico;
    }
    
    public void setPacEncaminhamentoMedico(String pacEncaminhamentoMedico) {
        this.pacEncaminhamentoMedico = pacEncaminhamentoMedico;
    }
    public String getPacPlanoSaude() {
        return this.pacPlanoSaude;
    }
    
    public void setPacPlanoSaude(String pacPlanoSaude) {
        this.pacPlanoSaude = pacPlanoSaude;
    }
    public String getPacTriadoPor() {
        return this.pacTriadoPor;
    }
    
    public void setPacTriadoPor(String pacTriadoPor) {
        this.pacTriadoPor = pacTriadoPor;
    }
    public Date getPacDataTriagem() {
        return this.pacDataTriagem;
    }
    
    public void setPacDataTriagem(Date pacDataTriagem) {
        this.pacDataTriagem = pacDataTriagem;
    }




}


