package pojos;
// Generated 20/09/2017 13:38:33 by Hibernate Tools 4.3.1



/**
 * TbTrauma generated by hbm2java
 */
public class TbTrauma  implements java.io.Serializable {


     private Integer traId;
     private String traVeicMotor;
     private String traForcDesac;
     private String traForcDesacDesc;
     private String traEjecaoVeic;
     private String traNegacao;
     private String traNegacaoDesc;
     private String traFraturaPrimCost;
     private String traFraturaPrimCostDesc;
     private String traFraturaSegCost;
     private String traFraturaSegCostDesc;
     private String traAspiracao;
     private String traAspiracaoDesc;
     private String traPerdaConsc;
     private String traPerdaConscDesc;
     private String traAcidMotocic;
     private String traAcidMotocicDesc;
     private String traContPulm;
     private String traObitoLocal;
     private String traAtropelamentoPed;
     private String traFraturaCost;
     private String traFraturaCostDesc;

    public TbTrauma() {
    }

	
    public TbTrauma(String traVeicMotor, String traForcDesac, String traEjecaoVeic, String traNegacao, String traFraturaPrimCost, String traFraturaSegCost, String traAspiracao, String traPerdaConsc, String traAcidMotocic, String traContPulm, String traObitoLocal, String traAtropelamentoPed, String traFraturaCost) {
        this.traVeicMotor = traVeicMotor;
        this.traForcDesac = traForcDesac;
        this.traEjecaoVeic = traEjecaoVeic;
        this.traNegacao = traNegacao;
        this.traFraturaPrimCost = traFraturaPrimCost;
        this.traFraturaSegCost = traFraturaSegCost;
        this.traAspiracao = traAspiracao;
        this.traPerdaConsc = traPerdaConsc;
        this.traAcidMotocic = traAcidMotocic;
        this.traContPulm = traContPulm;
        this.traObitoLocal = traObitoLocal;
        this.traAtropelamentoPed = traAtropelamentoPed;
        this.traFraturaCost = traFraturaCost;
    }
    public TbTrauma(String traVeicMotor, String traForcDesac, String traForcDesacDesc, String traEjecaoVeic, String traNegacao, String traNegacaoDesc, String traFraturaPrimCost, String traFraturaPrimCostDesc, String traFraturaSegCost, String traFraturaSegCostDesc, String traAspiracao, String traAspiracaoDesc, String traPerdaConsc, String traPerdaConscDesc, String traAcidMotocic, String traAcidMotocicDesc, String traContPulm, String traObitoLocal, String traAtropelamentoPed, String traFraturaCost, String traFraturaCostDesc) {
       this.traVeicMotor = traVeicMotor;
       this.traForcDesac = traForcDesac;
       this.traForcDesacDesc = traForcDesacDesc;
       this.traEjecaoVeic = traEjecaoVeic;
       this.traNegacao = traNegacao;
       this.traNegacaoDesc = traNegacaoDesc;
       this.traFraturaPrimCost = traFraturaPrimCost;
       this.traFraturaPrimCostDesc = traFraturaPrimCostDesc;
       this.traFraturaSegCost = traFraturaSegCost;
       this.traFraturaSegCostDesc = traFraturaSegCostDesc;
       this.traAspiracao = traAspiracao;
       this.traAspiracaoDesc = traAspiracaoDesc;
       this.traPerdaConsc = traPerdaConsc;
       this.traPerdaConscDesc = traPerdaConscDesc;
       this.traAcidMotocic = traAcidMotocic;
       this.traAcidMotocicDesc = traAcidMotocicDesc;
       this.traContPulm = traContPulm;
       this.traObitoLocal = traObitoLocal;
       this.traAtropelamentoPed = traAtropelamentoPed;
       this.traFraturaCost = traFraturaCost;
       this.traFraturaCostDesc = traFraturaCostDesc;
    }
   
    public Integer getTraId() {
        return this.traId;
    }
    
    public void setTraId(Integer traId) {
        this.traId = traId;
    }
    public String getTraVeicMotor() {
        return this.traVeicMotor;
    }
    
    public void setTraVeicMotor(String traVeicMotor) {
        this.traVeicMotor = traVeicMotor;
    }
    public String getTraForcDesac() {
        return this.traForcDesac;
    }
    
    public void setTraForcDesac(String traForcDesac) {
        this.traForcDesac = traForcDesac;
    }
    public String getTraForcDesacDesc() {
        return this.traForcDesacDesc;
    }
    
    public void setTraForcDesacDesc(String traForcDesacDesc) {
        this.traForcDesacDesc = traForcDesacDesc;
    }
    public String getTraEjecaoVeic() {
        return this.traEjecaoVeic;
    }
    
    public void setTraEjecaoVeic(String traEjecaoVeic) {
        this.traEjecaoVeic = traEjecaoVeic;
    }
    public String getTraNegacao() {
        return this.traNegacao;
    }
    
    public void setTraNegacao(String traNegacao) {
        this.traNegacao = traNegacao;
    }
    public String getTraNegacaoDesc() {
        return this.traNegacaoDesc;
    }
    
    public void setTraNegacaoDesc(String traNegacaoDesc) {
        this.traNegacaoDesc = traNegacaoDesc;
    }
    public String getTraFraturaPrimCost() {
        return this.traFraturaPrimCost;
    }
    
    public void setTraFraturaPrimCost(String traFraturaPrimCost) {
        this.traFraturaPrimCost = traFraturaPrimCost;
    }
    public String getTraFraturaPrimCostDesc() {
        return this.traFraturaPrimCostDesc;
    }
    
    public void setTraFraturaPrimCostDesc(String traFraturaPrimCostDesc) {
        this.traFraturaPrimCostDesc = traFraturaPrimCostDesc;
    }
    public String getTraFraturaSegCost() {
        return this.traFraturaSegCost;
    }
    
    public void setTraFraturaSegCost(String traFraturaSegCost) {
        this.traFraturaSegCost = traFraturaSegCost;
    }
    public String getTraFraturaSegCostDesc() {
        return this.traFraturaSegCostDesc;
    }
    
    public void setTraFraturaSegCostDesc(String traFraturaSegCostDesc) {
        this.traFraturaSegCostDesc = traFraturaSegCostDesc;
    }
    public String getTraAspiracao() {
        return this.traAspiracao;
    }
    
    public void setTraAspiracao(String traAspiracao) {
        this.traAspiracao = traAspiracao;
    }
    public String getTraAspiracaoDesc() {
        return this.traAspiracaoDesc;
    }
    
    public void setTraAspiracaoDesc(String traAspiracaoDesc) {
        this.traAspiracaoDesc = traAspiracaoDesc;
    }
    public String getTraPerdaConsc() {
        return this.traPerdaConsc;
    }
    
    public void setTraPerdaConsc(String traPerdaConsc) {
        this.traPerdaConsc = traPerdaConsc;
    }
    public String getTraPerdaConscDesc() {
        return this.traPerdaConscDesc;
    }
    
    public void setTraPerdaConscDesc(String traPerdaConscDesc) {
        this.traPerdaConscDesc = traPerdaConscDesc;
    }
    public String getTraAcidMotocic() {
        return this.traAcidMotocic;
    }
    
    public void setTraAcidMotocic(String traAcidMotocic) {
        this.traAcidMotocic = traAcidMotocic;
    }
    public String getTraAcidMotocicDesc() {
        return this.traAcidMotocicDesc;
    }
    
    public void setTraAcidMotocicDesc(String traAcidMotocicDesc) {
        this.traAcidMotocicDesc = traAcidMotocicDesc;
    }
    public String getTraContPulm() {
        return this.traContPulm;
    }
    
    public void setTraContPulm(String traContPulm) {
        this.traContPulm = traContPulm;
    }
    public String getTraObitoLocal() {
        return this.traObitoLocal;
    }
    
    public void setTraObitoLocal(String traObitoLocal) {
        this.traObitoLocal = traObitoLocal;
    }
    public String getTraAtropelamentoPed() {
        return this.traAtropelamentoPed;
    }
    
    public void setTraAtropelamentoPed(String traAtropelamentoPed) {
        this.traAtropelamentoPed = traAtropelamentoPed;
    }
    public String getTraFraturaCost() {
        return this.traFraturaCost;
    }
    
    public void setTraFraturaCost(String traFraturaCost) {
        this.traFraturaCost = traFraturaCost;
    }
    public String getTraFraturaCostDesc() {
        return this.traFraturaCostDesc;
    }
    
    public void setTraFraturaCostDesc(String traFraturaCostDesc) {
        this.traFraturaCostDesc = traFraturaCostDesc;
    }




}


